# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 620ac8c085aa13eddc3906e37e9aa8045d86353eaf7abc4077224d92a3214607f885e58d28522b24110d2a4c334f79163895d3b39e646034275e74659e5d7255

test:
  secret_key_base: 1779cbf2620d719fc43e9bc773eebc73e30bf7e4d05eba37c84f96094eeb9b325824244cd95a07fe94ce9405aa027f630e55212fea7c39b1075b042f8f60f45d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
